### ISSUE TITLE
Execute bash command before phpunit

### ISSUE THREAD

**Issue by nicosomb** [liip/RMT#114]
Hello,

Thank you for RMT. 
I want to execute some bash commands, for example `ant prepare` before my unit tests (to create a test environment). 
I read in #72 that it wasn't possible to launch actions written in bash but it was in 2014. 

Is that possible today?

**Comment by jeanmonod** [comment]
Hi @nicosomb,
There is a `command` action (missing from the documentation). I just add it: 5d427bd
Also as said in #72 you can easily write your own action.
I hope this help

**Comment by nicosomb** [comment]
Thank you 👍  !
