### ISSUE TITLE
Release a new version of RMT

### ISSUE THREAD

**Issue by nicwortel** [liip/RMT#119]
The composer.json of RMT has been updated in November 2016 to allow version 4.0 of sensiolabs/security-checker (#115), however there has been no release of RMT since then.

Can we get a new release of RMT so we can use RMT in combination with version 4.0 of the security checker?

**Comment by jeanmonod** [comment]
Here it is: https://github.com/liip/RMT/tree/1.2.7

**Comment by nicwortel** [comment]
Great, thanks for your work and for the quick response! :+1:
