### ISSUE TITLE
executeCommandInProcess should throw if the command fails

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/RMT#134]
The `BaseAction->executeCommandInProcess()` should throw an Exception in the same way as `CommandAction->execute()` [does](https://github.com/liip/RMT/blob/master/src/Liip/RMT/Action/CommandAction.php#L56-L59).

**Comment by jeanmonod** [comment]
@LeBenLeBen Could have been a way of doing things. But right now the `$process` is returned and it's the caller responsibility to do something with it. You can see an example here: https://github.com/liip/RMT/blob/master/src/Liip/RMT/Prerequisite/TestsCheck.php#L47

I'm not doing to change that now, as it will create a BC break. Sorry
