### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nicwortel** [liip/RMT#135]
Symfony 4 was [released](http://symfony.com/blog/hello-symfony-4) yesterday! :tada:

Liip RMT has been made compatible with Symfony 4 by #129, but this is only available in the master branch, not in a release. Tagging a new release should fix this and allow everyone to use Liip RMT with Symfony 4.

**Comment by nicwortel** [comment]
@dbu is there anything that needs to be done before the new version can be released? If I can help, please let me know!

**Comment by dbu** [comment]
indeed. i just released 1.3.0

@jeanmonod is the actual maintainer, but he is currently on paternal leave...
