### ISSUE TITLE
Abort tagging

### ISSUE THREAD

**Issue by core23** [liip/RMT#143]
Is it possible to abort the tagging dialog?

```
1) Please provide release type, can be major, minor or patch
    [m] major
    [i] minor
    [p] patch
```

In my release process I'll get a list of all changes and it could be possible that I want to cancel the release. How do I do this?

**Comment by krtek4** [comment]
`Ctrl+C`  aborts any running program in the terminal. It also works for `RMT` :)

**Comment by core23** [comment]
> `Ctrl+C` aborts any running program in the terminal. It also works for `RMT` :)

Not in my shell (zsh) :/

**Comment by krtek4** [comment]
According to what I can read in the documentation, zsh also uses `Ctrl+C` : http://zsh.sourceforge.net/Guide/zshguide03.html#l29

>>>
When you type ^C to stop a process, you are actually sending it a SIGINT for `interrupt', as if you had done
  kill -INT 8613

**Comment by ppetermann** [comment]
I'm using zsh, CTRL+C works fine for me.

**Comment by core23** [comment]
Okay, then it must be a Docker > ZSH problem. Thanks anyway
