### ISSUE TITLE
sensiolabs/security-checker is abandoned

### ISSUE THREAD

**Issue by lukey78** [liip/RMT#162]
I just wondered why my app is complaining as I don't have this package in my composer deps.

Turns out RMT is requiring it. Should be thrown out of the deps. Thank you!

**Comment by jeanmonod** [comment]
Thanks for reporting, we are going to check to replace that piece

**Comment by jeanmonod** [comment]
Released under https://github.com/liip/RMT/commit/87e0e9e109547b72f4ddaa44cf8d4a51cc55aa13
