### ISSUE TITLE
Error preventing release a new update

### ISSUE THREAD

**Issue by mateuslecchi** [liip/RMT#166]
I have a project with laravel that I recently upgrade  laravel 8>9. When a try to release a new version with RMT I got this error:

`PHP Fatal error:  Declaration of Liip\RMT\Application::run(?Symfony\Component\Console\Input\InputInterface $input = null, ?Symfony\Component\Console\Output\OutputInterface $output = null) must be compatible with Symfony\Component\Console\Application::run(?Symfony\Component\Console\Input\InputInterface $input = null, ?Symfony\Component\Console\Output\OutputInterface $output = null): int in /home/mateus/portal-novo/vendor/liip/rmt/src/Liip/RMT/Application.php on line 74`

I tried remove and reinstall the package and nothing works.

**Comment by mateuslecchi** [comment]
I've figured out, this error ocurs on Symfony/Console v6.0+, I've changed some files and make a PR.

**Comment by mateuslecchi** [comment]
This repo looks like is abandoned. Guys, are you maintain this repo?

**Comment by jeanmonod** [comment]
It's not abandoned, but not actively maintained, to be honest. And you were quite unlucky because my colleague and I were in holidays and in paternity leave on the previous weeks. I will take a look asap

**Comment by mateuslecchi** [comment]
Thank you for the answer, and I don't wanna to rush you. 

Best regards.

**Comment by jeanmonod** [comment]
@mateuslecchi A new release of RMT 1.7.0 is available with your fixes. Please let us know if you have issues
