### ISSUE TITLE
Error when using the composer-security-check prerequisite

### ISSUE THREAD

**Issue by jeanmonod** [liip/RMT#97]
Here is the output

    4) Composer Security Check : running composer security check

    [SensioLabs\Security\Exception\RuntimeException]
    An error occurred: SSL: certificate verification failed (result: 5).

**Comment by jeanmonod** [comment]
@ppetermann Any idea why we have this?

**Comment by ppetermann** [comment]
A guess would be a certificate problem, either old / missing root certs on the machine is run on, or  an invalid/outdated cert with the host it pulls the  data from. 

I'm currently mobile, so I can't reproduce - if it's Windows Google php certificate problem, if it isn't, I'm afraid it has to wait to tomorrow

**Comment by ppetermann** [comment]
I tried to reproduce it, however its working fine (on 3 different machines that i tested),
can you provide more information, like PHP version, operating system etc?

**Comment by jeanmonod** [comment]
Strange...
I'm on OSX 10.10.1 and with PHP 5.5.14
The full stack is 
```
Exception trace:
 () at /Users/dj/Projects/rmt/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php:101
 SensioLabs\Security\SecurityChecker->check() at /Users/dj/Projects/rmt/src/Liip/RMT/Prerequisite/ComposerSecurityCheck.php:43
 Liip\RMT\Prerequisite\ComposerSecurityCheck->execute() at /Users/dj/Projects/rmt/src/Liip/RMT/Command/ReleaseCommand.php:162
 Liip\RMT\Command\ReleaseCommand->executeActionListIfExist() at /Users/dj/Projects/rmt/src/Liip/RMT/Command/ReleaseCommand.php:88
 Liip\RMT\Command\ReleaseCommand->initialize() at /Users/dj/Projects/rmt/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:231
 Symfony\Component\Console\Command\Command->run() at /Users/dj/Projects/rmt/src/Liip/RMT/Command/BaseCommand.php:40
 Liip\RMT\Command\BaseCommand->run() at /Users/dj/Projects/rmt/vendor/symfony/console/Symfony/Component/Console/Application.php:889
 Symfony\Component\Console\Application->doRunCommand() at /Users/dj/Projects/rmt/vendor/symfony/console/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /Users/dj/Projects/rmt/vendor/symfony/console/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /Users/dj/Projects/rmt/src/Liip/RMT/Application.php:70
 Liip\RMT\Application->run() at /Users/dj/Projects/rmt/command.php:4
 require() at /Users/dj/Projects/rmt/RMT:6
```
Hope this help...

**Comment by ppetermann** [comment]
yah, thats curl failing at verification

can you check what your php.ini has set for:
openssl.cafile, and if that file exists?

if it doesn't, you can find on with current certs for curl at http://curl.haxx.se/ca/cacert.pem

**Comment by ppetermann** [comment]
did this fix your issue?

**Comment by ppetermann** [comment]
@jeanmonod any update on this?

**Comment by jeanmonod** [comment]
No, I never see this error again. I will close it, and let's re-open it if needed. Thanks for taking care of it
